name: Sync YAOF to YAOF

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout YAOF repository
        uses: actions/checkout@v2
        with:
          repository: oppen321/YAOF
          token: ${{ secrets.GITHUB_TOKEN }}
          path: YAOF
          ref: 23.05  # 指定分支

      - name: Checkout upstream YAOF repository
        uses: actions/checkout@v2
        with:
          repository: QiuSimons/YAOF
          token: ${{ secrets.GITHUB_TOKEN }}
          path: yaof
          ref: 23.05  # 指定分支

      - name: List directories
        run: |
          echo "Contents of YAOF directory:"
          ls -R YAOF
          echo "Contents of upstream YAOF directory:"
          ls -R yaof

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions"

      - name: Sync changes
        run: |
          echo "Contents of upstream YAOF directory:"
          ls -R yaof
          if [ -d yaof/23.05 ]; then
            cd YAOF
            git checkout 23.05 || git checkout -b 23.05  # 如果分支不存在，则创建它
            rsync -av --delete ../yaof/23.05/ ./
          else
            echo "Directory yaof/23.05 does not exist. Skipping sync."
          fi

      - name: Upload changes
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 使用存储的访问令牌
        run: |
          cd YAOF
          if git status --porcelain | grep .; then
            git add .
            git commit -m "Sync from upstream YAOF at $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
            git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/oppen321/YAOF.git" HEAD:23.05
          else
            echo "nothing to commit"
            exit 0
          fi || exit 0
